FROM golang:1.20

WORKDIR /go/src/app

COPY go.* ./

# Install required package
RUN go get -u github.com/go-sql-driver/mysql
RUN go get github.com/Shopify/sarama

COPY cmd cmd

RUN go build cmd/main.go

CMD ["./main"]