FROM golang:latest
WORKDIR /go/src/app
COPY /cmd/go.mod /go/src/app/

RUN go get -u github.com/gorilla/mux
RUN go get github.com/go-sql-driver/mysql

# CMD ["/bin/bash"]


# RUN go run /go/src/appmain.go
CMD go run /go/src/appmain.go